### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by antonmosich** [lunik1/nix-wallpaper#3]
242c2b7dac82f77d5b28672a4ac2097f2e5c8c8b made the wallpaper no longer build (via `nix build`) and fail with `magick: no images found for operation '-resize' at CLI arg 1 @ error/operation.c/CLIOption/5481`.
You can fix the compilation by moving the `wallpaper.svg` from the end of the command to the beginning,  so you're calling `magick wallpaper.svg [options] $out/...`. The image that is produced that way is not what _should_ come out though, and I don't want to delve into imagemagick options right now, so an issue it is :)

**Comment by lunik1** [comment]
Not much luck reproducing the current wallpapers with imagemagick 7 here either, so have switched  to `magick convert` for now.

**Comment by lunik1** [comment]
ImageMagick 7 is being tracked in #4 now
